apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: starbucks
  template:
    metadata:
      labels:
        app: starbucks
    spec:
      containers:
      - name: starbucks-container
        image: waseem09/starbucks:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: starbucks-service
spec:
  type: NodePort
  selector:
    app: starbucks
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001

